function [ output_args ] = create_html_file_osm( filename, rx_lat, rx_long )
%CREATE_HTML_FILE   Generates the html code for open street map showing RX
%                   positions and the hyperbolas
%
%   rx_lat:         list of latitudes for RX positions (for displaying receiver positions)
%   rx_long:        list of longitudes for RX positions
%   hyperbola_lat:  cell array of latitudes for RX positions (one cell array elements correspond to one hyperbola)
%   hyperbola_lat:  cell array of longitudes for RX positions (one cell array elements correspond to one hyperbola)

    disp('writing html for OSM... ');

    % consistency checks
    

    if size(rx_lat) ~= size(rx_long)
        error('Dimensions of rx latitude and longitude values do not match');
    end
    
    
    num_rx_positions = length(rx_lat);


    %% generate html code
    disp(['write html to file: ' filename]);

    fid = fopen(filename,'w');
  
    fprintf(fid, [...
        '<!DOCTYPE html>\n'...
        '<html>\n'...
		'\n'...
		'<head>\n'...
	    '<title>Simple Leaflet Map</title>\n'...
	    '<meta charset="utf-8" />\n'...
	    '<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7/leaflet.css"/>\n'...
        '</head>\n'...
        '\n'...
        '<body>\n'...
        '\n'...
        '<div id="map" style="width:100%%;height:800px"></div>\n'...
        '\n'...
        '<script src="http://cdn.leafletjs.com/leaflet-0.7/leaflet.js"> </script>\n'...
        '\n'...
        '<script>\n'...
		'  var map = L.map("map").setView([ ' num2str(mean(rx_lat), 8) ', ' num2str(mean(rx_long), 8) '], 13); \n'...
		'  mapLink = \''<a href="http://openstreetmap.org">OpenStreetMap</a>\'';\n'...
		' \n'...
		'  L.tileLayer(\n'...
		'    "http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {\n'...
	    '	  attribution: "Map data &copy; " + mapLink,\n'...
		'	  maxZoom: 18,\n'...
		'	  }).addTo(map)\n'...
        '  L.control.scale().addTo(map);\n'...
        ]);

    fprintf(fid, '\n');
    
    %% write RX positions to html file
    for ii = 1:num_rx_positions
        fprintf(fid, ['  var marker_rx' num2str(ii) ' = L.marker([' num2str(rx_lat(ii), 8) ', ' num2str(rx_long(ii), 8) '], \n'...
                      '                            {title: \'' Receiver ' int2str(ii) ' \''}) \n'...     % label when user hovers over marker
                      '                            .addTo(map) \n'...
                      '                            .bindPopup(\''Receiver ' int2str(ii) ' \''); \n\n']); % label when user klicks on marker
    end;

    
    %% footer
    
    fprintf(fid, [...
        '\n'...
        '</script>\n'...
        '</body>\n'...
        '</html>\n'...
        '\n'...
        ]);

    fclose(fid);
    
    disp('writing html, done!');
end

